# Generated by Django 3.0.2 on 2020-01-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=256)),
                ('VkUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vktoken.VkUser')),
            ],
        ),
    ]
