# Generated by Django 3.0.2 on 2020-01-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vktoken', '0001_make_vk_user_and_vktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkuser',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='VkToken',
        ),
    ]
